# Smoke detection with GBC - Acc 0.99


* **1. Introduction**

* **2. Data preparation**
    * 2.1 Import libraries
    * 2.2 Load data
    * 2.3 Describtion 
    * 2.4 Check for null
    * 2.5 Target
    
* **3. KFold and Gradient Boosting Classifier**
    * 3.1 Define the models 
    * Spliting Predicting Confusion Matrix Accuracy

# 1.Introduction


On this code we should do a classification for the target(fire alarm).
I used Gradient Boosting Classifier algorithme for classifing the target
and i used KFold for get good training and testing. 



# 2. Data preparation :

## 2.1 Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.ensemble import GradientBoostingClassifier

## 2.2 Load data

In [2]:
Data = pd.read_csv('./smoke.csv')
Data.head(5000)

Unnamed: 0         UTC  Temperature[C]  Humidity[%]  TVOC[ppb]  \
0              0  1654733331          20.000        57.36          0   
1              1  1654733332          20.015        56.67          0   
2              2  1654733333          20.029        55.96          0   
3              3  1654733334          20.044        55.28          0   
4              4  1654733335          20.059        54.69          0   
...          ...         ...             ...          ...        ...   
4995        4995  1654738326          -8.308        49.24         43   
4996        4996  1654738327          -8.312        49.08         42   
4997        4997  1654738328          -8.316        48.92         54   
4998        4998  1654738329          -8.321        48.85         50   
4999        4999  1654738330          -8.325        48.73         48   

      eCO2[ppm]  Raw H2  Raw Ethanol  Pressure[hPa]  PM1.0  PM2.5  NC0.5  \
0           400   12306        18520        939.735   0.00   0.00   0.00   
1           400   12345        18651        939.744   0.00   0.00   0.00   
2           400   12374        18764        939.738   0.00   0.00   0.00   
3           400   12390        18849        939.736   0.00   0.00   0.00   
4           400   12403        18921        939.744   0.00   0.00   0.00   
...         ...     ...          ...            ...    ...    ...    ...   
4995        400   13238        20169        939.692   2.22   2.31  15.30   
4996        400   13243        20177        939.690   2.26   2.35  15.58   
4997        400   13244        20180        939.688   2.35   2.44  16.17   
4998        400   13236        20166        939.686   2.41   2.50  16.58   
4999        400   13236        20177        939.685   2.47   2.57  17.03   

      NC1.0  NC2.5   CNT  Fire Alarm  
0     0.000  0.000     0           0  
1     0.000  0.000     1           0  
2     0.000  0.000     2           0  
3     0.000  0.000     3           0  
4     0.000  0.000     4           0  
...     ...    ...   ...         ...  
4995  2.385  0.054  4995           1  
4996  2.429  0.055  4996           1  
4997  2.522  0.057  4997           1  
4998  2.585  0.058  4998           1  
4999  2.655  0.060  4999           1  

[5000 rows x 16 columns]

## 2.3 Describtion

In [3]:
Data['Fire Alarm'].describe()

count    62630.000000
mean         0.714626
std          0.451596
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: Fire Alarm, dtype: float64

## 2.4 Check for null

In [4]:
total = Data.isnull().sum().sort_values(ascending=False)
percent=(Data.isnull().sum()/Data.isnull().count()).sort_values(ascending=False)
missingData = pd.concat([total,percent],axis=1,keys=['Total','Percent'])
missingData.head(15)

Total  Percent
Unnamed: 0          0      0.0
UTC                 0      0.0
Temperature[C]      0      0.0
Humidity[%]         0      0.0
TVOC[ppb]           0      0.0
eCO2[ppm]           0      0.0
Raw H2              0      0.0
Raw Ethanol         0      0.0
Pressure[hPa]       0      0.0
PM1.0               0      0.0
PM2.5               0      0.0
NC0.5               0      0.0
NC1.0               0      0.0
NC2.5               0      0.0
CNT                 0      0.0

## 2.5 Get target

In [5]:
X = Data.iloc[:,:-1]
Y = Data.iloc[:,-1]

In [6]:
X

Unnamed: 0         UTC  Temperature[C]  Humidity[%]  TVOC[ppb]  \
0               0  1654733331          20.000        57.36          0   
1               1  1654733332          20.015        56.67          0   
2               2  1654733333          20.029        55.96          0   
3               3  1654733334          20.044        55.28          0   
4               4  1654733335          20.059        54.69          0   
...           ...         ...             ...          ...        ...   
62625       62625  1655130047          18.438        15.79        625   
62626       62626  1655130048          18.653        15.87        612   
62627       62627  1655130049          18.867        15.84        627   
62628       62628  1655130050          19.083        16.04        638   
62629       62629  1655130051          19.299        16.52        643   

       eCO2[ppm]  Raw H2  Raw Ethanol  Pressure[hPa]  PM1.0  PM2.5  NC0.5  \
0            400   12306        18520        939.735   0.00   0.00   0.00   
1            400   12345        18651        939.744   0.00   0.00   0.00   
2            400   12374        18764        939.738   0.00   0.00   0.00   
3            400   12390        18849        939.736   0.00   0.00   0.00   
4            400   12403        18921        939.744   0.00   0.00   0.00   
...          ...     ...          ...            ...    ...    ...    ...   
62625        400   13723        20569        936.670   0.63   0.65   4.32   
62626        400   13731        20588        936.678   0.61   0.63   4.18   
62627        400   13725        20582        936.687   0.57   0.60   3.95   
62628        400   13712        20566        936.680   0.57   0.59   3.92   
62629        400   13696        20543        936.676   0.57   0.59   3.90   

       NC1.0  NC2.5   CNT  
0      0.000  0.000     0  
1      0.000  0.000     1  
2      0.000  0.000     2  
3      0.000  0.000     3  
4      0.000  0.000     4  
...      ...    ...   ...  
62625  0.673  0.015  5739  
62626  0.652  0.015  5740  
62627  0.617  0.014  5741  
62628  0.611  0.014  5742  
62629  0.607  0.014  5743  

[62630 rows x 15 columns]

In [7]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
62625    0
62626    0
62627    0
62628    0
62629    0
Name: Fire Alarm, Length: 62630, dtype: int64

## KFold and Gradient boosting classifier


#### Gradient Boosting Classifier:

Gradient boosting classifier is a machine learning technique used in regression and classification tasks among others it gives a predict model in the form of an ensemble of weak prediction models .


--------------------------------------------------------------------------------------------------------------

#### KFold:

KFolds cross validation 
Provides train/test indices to split data train/test. Split dataset into k consecutive folds (without shuffling by default).
Each fold is then used once as a vlidation while the k-1 remining folds form the trainig set.

<center><img src ="https://upload.wikimedia.org/wikipedia/commons/b/b5/K-fold_cross_validation_EN.svg" /></center>

In [8]:
KFModel = StratifiedKFold(n_splits=5)
p_rf= np.zeros(Y.shape[0])

In [9]:
for n in range(10,100,10):
    for train,test in KFModel.split(X,Y):
        X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=33)
        clf = GradientBoostingClassifier(n_estimators=100,learning_rate=1.0,max_depth=1,random_state=33)
        clf.fit(X_train,Y_train)
        Y_pred = clf.predict(X_test)
        cm=confusion_matrix(Y_test,Y_pred)
        print(cm)
    print('Score for n:','',accuracy_score(Y_test,Y_pred))

[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
Score for n:  0.9999201660546064
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
Score for n:  0.9999201660546064
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
Score for n:  0.9999201660546064
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
Score for n:  0.9999201660546064
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
Score for n:  0.9999201660546064
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
[[3624    1]
 [   0 8901]]
Score for n:  0.999920166